"""empty message

Revision ID: e8d65f5b1e0a
Revises: 9d16bbd5f98e
Create Date: 2025-12-30 22:09:13.702749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d65f5b1e0a'
down_revision = '9d16bbd5f98e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorites',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('place_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###
